/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/Index" |
  "/pages/mine/Index" |
  "/pages/test/Index" |
  "/pages-design/a/a" |
  "/pages-design/actionSheet/actionSheet" |
  "/pages-design/addressPicker/addressPicker" |
  "/pages-design/avatar/avatar" |
  "/pages-design/backTop/backTop" |
  "/pages-design/badge/badge" |
  "/pages-design/button/button" |
  "/pages-design/calendar/calendar" |
  "/pages-design/card/card" |
  "/pages-design/cell/cell" |
  "/pages-design/checkbox/checkbox" |
  "/pages-design/checkButton/checkButton" |
  "/pages-design/codeInput/codeInput" |
  "/pages-design/configProvider/configProvider" |
  "/pages-design/countDown/countDown" |
  "/pages-design/countTo/countTo" |
  "/pages-design/coupon/coupon" |
  "/pages-design/datetimePicker/datetimePicker" |
  "/pages-design/divider/divider" |
  "/pages-design/dropdown/dropdown" |
  "/pages-design/empty/empty" |
  "/pages-design/flex/flex" |
  "/pages-design/floatButton/floatButton" |
  "/pages-design/foldingPanel/foldingPanel" |
  "/pages-design/form/form" |
  "/pages-design/formGroup/formGroup" |
  "/pages-design/grid/grid" |
  "/pages-design/icon/icon" |
  "/pages-design/image/image" |
  "/pages-design/indexBar/indexBar" |
  "/pages-design/input/input" |
  "/pages-design/line/line" |
  "/pages-design/lineProgress/lineProgress" |
  "/pages-design/list/list" |
  "/pages-design/loading/loading" |
  "/pages-design/menu/menu" |
  "/pages-design/modal/modal" |
  "/pages-design/navbar/navbar" |
  "/pages-design/noticeBar/noticeBar" |
  "/pages-design/notify/notify" |
  "/pages-design/numberBox/numberBox" |
  "/pages-design/overlay/overlay" |
  "/pages-design/pagination/pagination" |
  "/pages-design/parse/parse" |
  "/pages-design/picker/picker" |
  "/pages-design/popover/popover" |
  "/pages-design/popup/popup" |
  "/pages-design/price/price" |
  "/pages-design/qrcode/qrcode" |
  "/pages-design/radio/radio" |
  "/pages-design/rate/rate" |
  "/pages-design/readMore/readMore" |
  "/pages-design/rollingNum/rollingNum" |
  "/pages-design/scrollList/scrollList" |
  "/pages-design/search/search" |
  "/pages-design/signature/signature" |
  "/pages-design/skeleton/skeleton" |
  "/pages-design/slider/slider" |
  "/pages-design/steps/steps" |
  "/pages-design/sticky/sticky" |
  "/pages-design/submitBar/submitBar" |
  "/pages-design/subsection/subsection" |
  "/pages-design/swipeAction/swipeAction" |
  "/pages-design/swiper/swiper" |
  "/pages-design/switch/switch" |
  "/pages-design/tabBar/tabBar" |
  "/pages-design/table/table" |
  "/pages-design/tabs/tabs" |
  "/pages-design/tag/tag" |
  "/pages-design/text/text" |
  "/pages-design/textarea/textarea" |
  "/pages-design/toast/toast" |
  "/pages-design/tooltip/tooltip" |
  "/pages-design/transition/transition" |
  "/pages-design/upload/upload" |
  "/pages-design/warn/warn" |
  "/pages-design/waterfall/waterfall" |
  "/pages-design/watermark/watermark";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/Index" | "/pages/mine/Index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
